menu:
  # Home: /
  Archives: /archives
  #Me: /me

widgets:
- search
- tag
- links
- recent_posts

excerpt_link: Read More

# Links
links:
  Dribbble: https://dribbble.com
  Awwwards: http://www.awwwards.com
  Emmet: http://docs.emmet.io/
  Hexo: http://hexo.io/
  One-Div: http://one-div.com/
  Ole-Begemann: http://oleb.net/
  NSHipster: http://nshipster.com/
  Cocoapods: http://cocoapods.org/

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
